
name: Latest Shop Products
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest shop products
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in marsad.dev products
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "Products"
          feed_list: "https://marsad.dev/shop/feed/"
